package Ext;

import java.math.*;
import java.security.*;
import java.util.Scanner;

public class Program_11_SHA {
    public static void main(String args[]) throws NoSuchAlgorithmException {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the plain text");
        String s = sc.nextLine();
        MessageDigest md = MessageDigest.getInstance("SHA-1");
        byte[] messageDigest = md.digest(s.getBytes());
        BigInteger no = new BigInteger(1, messageDigest);
        String hashtext = no.toString(16);
        // while (hashtext.length() < 32) {
        // hashtext = "0" + hashtext;
        // }
        System.out.println("HashCode Generated by SHA-1 for:\n" + s + " : " + hashtext);
        sc.close();
    }
}
